#!/bin/sh

## leave out ecdsa by default
hostkeys="
  /etc/ssh/ssh_host_rsa_key
  /etc/ssh/ssh_host_ed25519_key
"
## /etc/ssh/ssh_host_ecdsa_key

if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
	ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" < /dev/null
fi
if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
	ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" < /dev/null
fi

# for hostkey in $hostkeys; do
#   if [ ! -f "$hostkey" ]; then
#     echo "Generating host keys" >&2
#     /usr/bin/ssh-keygen -A
#   fi
# done

chmod -R 600 /etc/ssh/ssh_host_*key
chmod -R 644 /etc/ssh/ssh_host_*key.pub
chown borg:borg /home/borg/.ssh/authorized_keys
chmod -R 600 /home/borg/.ssh/authorized_keys

su - borg
exec "$@"
